services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "9091:9091"
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "9093:9093"
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "9092:9092"
    depends_on:
      - user-service
      - notification-service
    restart: unless-stopped
